// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfh9yMiELigduljPhKj0KqlPsaZc-95UI',
    appId: '1:605281237568:android:a7ee8b17a5ded8cf1cbda5',
    messagingSenderId: '605281237568',
    projectId: 'ufit-3771b',
    storageBucket: 'ufit-3771b.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwv6Jzq-4PhD-2M7ehiEYeoklbVKPiAps',
    appId: '1:605281237568:web:52dd059957ea21291cbda5',
    messagingSenderId: '605281237568',
    projectId: 'ufit-3771b',
    authDomain: 'ufit-3771b.firebaseapp.com',
    storageBucket: 'ufit-3771b.firebasestorage.app',
    measurementId: 'G-SRBK14KNXH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4gpJLDrXifk2DunuuxnBoXtIHRULmghE',
    appId: '1:605281237568:ios:1edb1e760885b25c1cbda5',
    messagingSenderId: '605281237568',
    projectId: 'ufit-3771b',
    storageBucket: 'ufit-3771b.firebasestorage.app',
    androidClientId: '605281237568-5v0t1n3bp3ksgru7qtro54fhvh1a8561.apps.googleusercontent.com',
    iosClientId: '605281237568-ffq6g8l8df2oo0jgpjr5n2ehectnv0b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufit',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4gpJLDrXifk2DunuuxnBoXtIHRULmghE',
    appId: '1:605281237568:ios:d8962678a0a937a21cbda5',
    messagingSenderId: '605281237568',
    projectId: 'ufit-3771b',
    storageBucket: 'ufit-3771b.firebasestorage.app',
    androidClientId: '605281237568-5v0t1n3bp3ksgru7qtro54fhvh1a8561.apps.googleusercontent.com',
    iosClientId: '605281237568-24cba3442ubbjq08snv7qp6vpquobqhi.apps.googleusercontent.com',
    iosBundleId: 'com.fittrack.ufit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwv6Jzq-4PhD-2M7ehiEYeoklbVKPiAps',
    appId: '1:605281237568:web:f6a4ec52645820fb1cbda5',
    messagingSenderId: '605281237568',
    projectId: 'ufit-3771b',
    authDomain: 'ufit-3771b.firebaseapp.com',
    storageBucket: 'ufit-3771b.firebasestorage.app',
    measurementId: 'G-7WS8YVN929',
  );
}
